import os
import sys

# Lazy importing mlx_lm only when initialized to prevent startup import crashes
model_instance = None

class MedGemmaService:
    _instance = None
    _model = None
    _tokenizer = None
    _initialized = False

    @classmethod
    def get_instance(cls):
        if cls._instance is None:
            cls._instance = MedGemmaService()
        return cls._instance

    def initialize(self):
        if self._initialized:
            return True
        
        model_id = "Goraint/medgemma-4b-it-MLX-AWQ-4bit"
        print(f"[MedGemmaService] Initializing local MLX GPU-accelerated model: {model_id}")
        
        try:
            from mlx_lm import load
            self._model, self._tokenizer = load(model_id)
            self._initialized = True
            print("[MedGemmaService] Model successfully loaded in local Metal memory.")
            return True
        except Exception as e:
            print(f"[MedGemmaService] Error loading model: {e}")
            self._initialized = False
            return False

    def generate_reasoning(self, grade: str, patient_info: dict, history_text: str) -> str:
        """
        Generates real visual-linguistic clinical reasoning on tissue morphology + FHIR history.
        """
        if not self._initialized:
            success = self.initialize()
            if not success:
                return "Resident Agent local GPU inference offline. Check MLX-LM environment."

        try:
            from mlx_lm import generate
            
            # Format high-fidelity prompt for MedGemma
            prompt = f"""<system>You are OncoPathAI's Senior Resident Pathology Agent. Explain the colorectal histopathology findings.</system>
<user>
Histopathology Slide Grade: {grade}
Patient Profile: {patient_info.get('name', 'Anonymous')} ({patient_info.get('age', 'N/A')}, {patient_info.get('gender', 'unknown')})
Clinical Patient History: {history_text}

Analyze the tissue architecture (crypt disorganization vs. basal polarity columns) and clinical context. Generate a concise, expert 3-sentence diagnostic summary explaining the predicted grade and mapping the recommended clinical pathway.
</user>
<assistant>"""
            
            print(f"[MedGemmaService] Executing real-time MLX local GPU inference...")
            response = generate(
                self._model,
                self._tokenizer,
                prompt=prompt,
                max_tokens=150,
                verbose=False
            )
            
            cleaned_res = response.strip()
            # If model prints assistant tags at the beginning, trim them
            if "<assistant>" in cleaned_res:
                cleaned_res = cleaned_res.split("<assistant>")[-1].strip()
            
            # Strip trailing tags or recursive prompts generated by the model
            for tag in ["</assistant>", "<system>", "</system>", "<user>", "</user>", "<assistant>"]:
                if tag in cleaned_res:
                    cleaned_res = cleaned_res.split(tag)[0].strip()
            return cleaned_res
            
        except Exception as e:
            print(f"[MedGemmaService] Inference execution failed: {e}")
            return f"Inference execution failed locally. Error: {str(e)}"
